### ISSUE TITLE
How to download jar/lib Git Project with Maven..

### ISSUE THREAD

**Issue by Code21k** [BelajarJavaBareng/bpersonalia#20]
i've tried many ways and search from search engine,, 
and most of answer -> update project (this is just for maven project and our project is git project so this solution couldnt work)

please someone tell me if i shall download manual or there is other way?

**Comment by byanto** [comment]
@Code21k you can do following steps:
1. Clone this project to the local computer, either use `git clone git@github.com:BelajarJavaBareng/bpersonalia.git` or `git clone https://github.com/BelajarJavaBareng/bpersonalia.git`
2. Import it in Eclipse as Existing Maven Project
3. Build it with Maven to let Maven download all of the dependencies automatically.

Note: Git and Maven are two different tools. Maven is used to handle all of the dependencies whereas Git is used to do versioning of source code. Since Maven is used in this project, you don't have to download all the jar/lib manually, Maven will handle it for you.

Hope it can help.

**Comment by Code21k** [comment]
this notice appear when i wanted to import maven project.
 Scanning errors (1):
  1 Could not read pom.xml

**Comment by byanto** [comment]
can you please try to clone the project again? it seems that you are missing the pom.xml file.

**Comment by Code21k** [comment]
yep it works, but i have a new problem now.. error when i want to pull stream.
Error Message :
Permission denied(public key).
Fatal : Could not read from remote repository

please make sure you have the correct access rights
and the repository exists.


i've tried :
- Remove my ssh key in github account
- Generate public key again
- Put the key to my github account again..

and the error doesnt fix.

do u have a solution for my prob? btw thanks for ur help for maven issue..

**Comment by byanto** [comment]
i'm glad to hear that you solve the problem. Don't hesitate to ask any question if you have a problem, i will try my best to help if i can. I think you can close this issue now, right?

**Comment by Code21k** [comment]
ok thanks..
